{{- if .Values.rbac.enabled }}
{{- if .Values.rbac.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "keel.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "keel.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccount.name" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
{{ end }}
