apiVersion: v1
name: keel
description: Open source tool for automating Kubernetes deployment updates.
version: 1.0.5
appVersion: 0.20.0
keywords:
- kubernetes deployment
- helm release
- continuous deployment
home: https://github.com/keel-hq/keel
sources:
- https://github.com/keel-hq/keel
engine: gotpl
icon: https://raw.githubusercontent.com/keel-hq/keel/master/static/keel-logo.png
